apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "Ogbu11",
          "password": "ghp_9Nh6gZAEJYq9iLkGHq4y8UDVzJ7Usb1hA0yD",
          "email": "mikelsunny2@gmail.com",
          "auth": "T2didTExOmdocF85Tmg2Z1pBRUpZcTlpTGtHUTR5OFVEVnpKN1VzYjFoQTB5RA=="
        }
      }
    }
