apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: taskapp
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: database_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: database_password
          ports:
            - containerPort: 5432
              name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-backend
  namespace: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp-backend
  template:
    metadata:
      labels:
        app: taskapp-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: taskapp-config
            - secretRef:
                name: taskapp-secret
